version: '3.4'

services:
  appbuild1react:
    image: appbuild1react
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
